### PR TITLE
(#239) - fix dep dbs with db/prefix option

### PR DESCRIPTION
**Pull request by nolanlawson**
This will not be green until https://github.com/pouchdb/pouchdb/pull/3340 is merged.

### CODE REVIEW

**Comment by nolanlawson** [comment]
This will not be green until https://github.com/pouchdb/pouchdb/pull/3340 is merged.

**Comment by nolanlawson** [comment]
woo hoo, green!

**Comment by marten-de-vries** [comment]
So mapreduce isn't really my area of expertise, but it should suffice for this. Nice fix. :+1:

**Comment by nolanlawson** [comment]
cool, thanks!

**Pull request merged**
