### PR TITLE
WIP - really abstractify

### PR DESCRIPTION
**Pull request by nolanlawson**
OK guys, I think I have a solution where we can actually re-use map/reduce for the Cloudant Query thing, as well as FTS search, geo search, no-eval, etc.

I've written [abstract-mapreduce](https://github.com/nolanlawson/pouchdb-abstract-mapreduce), which pulls out the essential functionality and exposes an API like this:

```js
var abstractMapReduce = require('pouchdb-abstract-mapreduce');

var abstract = abstractMapReduce({
  name: 'mrviews',
  // ^ this is for the local doc that gets saved in order to track the "dependent" DBs
  // and clean them up for viewCleanup.
  // it should be unique, so that indexer plugins don't collide with each other
  mapper: function (mapFunDef, emit) {
    // return a mapFun based on the mapFunDef, which in the case of normal map/reduce
    // is just the de-stringified function, but may be something else
  },
  reducer:  function (reduceFunDef) {
    // ditto, but for reducing. maybe your module doesn't support reducing, in which case
    // you can just do nothing
  },
  ddocValidator: function (ddoc, viewName) {
    // throw an error if the ddoc or viewName is not to your liking
    // this could be a way to communicate to the user that your plugin doesn't support
    // reducing, or requires some additional metadata, or whatever
  }
});
```

It returns an object like

```js
{
  query: queryFun,
  viewCleanup: viewCleanupFun
}
```
...so each plugin has its own `query()` function and `viewCleanup()` function that it can export. Yes, the views have to be cleaned up separately, unless we want every indexer plugin to be able to delete the other plugins' indexes (which I think is dangerous).

What do you think? I already have passing unit tests and code coverage in both projects (and yes, Istanbul is still covering both codebases!!)

### CODE REVIEW

**Comment by marten-de-vries** [comment]
Very, very nice! I like it and the code that's left in this module seems good (not that it is much :stuck_out_tongue:), but probably good to hear from others too for such a huge change. I have only one use case where I'm not yet sure how it should be handled with this approach:

Soon we will probably have a coffeeQuery() and a query(). In express-pouchdb, we could just call the first, and if an error throws, the second. BUT: http is still only implemented in query(), so a coffeescript view will always be executed offline in that case. I see two solutions, either splitting out the http logic in a, say, pouchdb-mapreduce-http so others can reuse it, or making the main mapreduce check for ```(ddoc.language || "javascript") === javascript``` and otherwise throw an error (in which case it can be called first and handle the http case.) Both solutions can wait for later and don't have to keep up this PR, but I wanted to name them.

**Comment by nolanlawson** [comment]
For express-pouchdb, the http stuff is only useful when used as a proxy, right?

I would be happy to publish a pouchdb-mapreduce-http module. It seems the cleanest.

**Comment by nolanlawson** [comment]
Another thing that occurred to me: from the user's point of view, `viewCleanup` should probably clean up absolutely all views. I think we can accomplish this by having each module override the existing `viewCleanup`, then when it overrides, it can just replace it with a `Promise.all` to do both `viewCleanup`s. Make sense?

**Comment by marten-de-vries** [comment]
@nolanlawson Yes, only for proxy for express-pouchdb, which is not that much of a priority. The same situation might occur in the browser of a clueless user, though. Actually, it might not be a bad idea to do both a pouchdb-mapreduce-http & the ddoc.language check. That way the end user gets a clearer error & other plug-ins can still share the http stuff.

As for ``viewCleanup()``, I agree with the general idea, but you need to take into account classic callbacks next to promises. pouchdb-wrappers or a new similar ``viewCleanup()`` specific module could abstract that away though.

**Comment by nolanlawson** [comment]
No prob about callbacks vs. promises; that's all handled under the hood.

**Comment by marten-de-vries** [comment]
I just played a bit with the new API. The test case was building an alternative to mapreduce.noeval using my [evaljs library](https://www.npmjs.com/package/evaljs). It went pretty well.

I did notice one thing: the ``mapper`` function (and ``reduce`` too) doesn't get enough info for a valid implementation: you need access to the design document for that. Mostly because ``this`` points to the design doc in CouchDB and for a ``require()`` implementation. These are two things pouchdb mapreduce doesn't support so it's logical it's not there, but it might limit other implementations.

I don't know if ``viewName`` would be required too for something inside mapper/reduce functions, but to be sure it might be good to include it there too. The API would become:

```javascript
{
  mapper: function (mapFunDef, emit[, ddoc, viewName]),
  reducer: function (reduceFunDef[, ddoc, viewName])
}
```

With directly passed in objects there is of course no design doc, so I made the new arguments optional in this proposal.

[evaljs mapreduce experiment gist](https://gist.github.com/marten-de-vries/f938337b94773112d7b5)

----

@nolanlawson Callbacks are handled under the hood for ``exports.evaljsQuery`` in the above example, but adding a new ``PouchDB.prototype.query`` implementation that would call both the one already there and mine wouldn't be handled automatically, right?

**Comment by nolanlawson** [comment]
@marten-de-vries makes sense to me. I'll make those changes. Also, evaljs looks cool!

**Comment by nolanlawson** [comment]
> @nolanlawson Callbacks are handled under the hood for exports.evaljsQuery in the above example, but adding a new PouchDB.prototype.query implementation that would call both the one already there and mine wouldn't be handled automatically, right?

Right. You'd have to write that yourself; we have various helpers in mapreduce like `callbackify` and `toPromise` that can do that.

**Comment by marten-de-vries** [comment]
Ok, with helpers it's trivial indeed. :)

**Comment by nolanlawson** [comment]
Crap, it's going to be tough to pass the entire ddoc to the mapper/reducer. Are you sure you need it?

**Comment by marten-de-vries** [comment]
Well, it's not a blocker since the current implementation doesn't use the design doc either, but I can see it be necessary in the future. For Common JS mods chiefly (#220).

**Comment by nolanlawson** [comment]
Let's put it on the back burner, then. We can always add it into the API later. For everything else, I don't think it's necessary.

Basically I would need to modify `pouchdb-upsert` to return the full, updated doc in the result it passes to the client. Not a big deal; I'll file an issue.

**Comment by nolanlawson** [comment]
I'm going to use a similar solution, but in the end this will be solved by native indexes. Closing.

**Pull request closed without merging**
