### PR TITLE
Mulitple emissions of complex keys collapse

### PR DESCRIPTION
**Pull request by carlo-colombo**
Same as #14 but for complex keys. It should be a regression somewhere from 2.2.0 to 3.2.0.
I use collate from pouchdb-collate to make a deep comparison between the key we are analyzing and the previous one.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Great catch! You have some jshint errors, though. If you fix them I'm pretty sure the build will succeed.

**Comment by carlo-colombo** [comment]
Sorry for the multiple commits.

**Comment by nolanlawson** [comment]
no prob, I'll squash them together and then merge. thanks a million for this!

**Comment by nolanlawson** [comment]
8c34017adb5921f13bf3faba836e324470ff63e7

**Comment by carlo-colombo** [comment]
you are welcome

**Pull request closed without merging**
